version: '3'
services:
  app: 
    build: ./
    image: mk5306/glossary
    container_name: glossary-mk
    ports:
      - "80:3000" 
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    restart: always
    stdin_open: true
    tty: true
volumes:
  db:
